
#ifdef XCVAR_PROTO
	#define XCVAR_DEF( name, defVal, flags, desc ) extern vmCvar_t name;
#endif

#ifdef XCVAR_DECL
	#define XCVAR_DEF( name, defVal, flags, desc ) vmCvar_t name;
#endif

#ifdef XCVAR_LIST
	#define XCVAR_DEF( name, defVal, flags, desc ) { & name , #name , defVal , flags , desc },
#endif

XCVAR_DEF( bg_synchronousClients,			"0",					CVAR_SYSTEMINFO,			NULL )
XCVAR_DEF( cg_autoswitch,					"0",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_brightModels,					"1",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_centertime,					"2",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_crosshairColour,				"1 1 1",				CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_crosshairCooldownSpread,		"16",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_crosshairCooldownTics,		"16",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_crosshairCooldownWeapons,		"27",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_crosshairDisableZoomed,		"0",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_crosshairFeedbackColour,		"1 0 0",				CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_crosshairFeedbackTime,		"200",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_crosshairHealth,				"0",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_crosshairSize,				"24",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_currentSelectedPlayer,		"-1",					CVAR_NONE,					NULL )
XCVAR_DEF( cg_currentSelectedPlayerName,	"",						CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_damageViewKick,				"0",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_debugEvents,					"0",					CVAR_NONE,					NULL )
XCVAR_DEF( cg_debugHUD,						"0",					CVAR_NONE,					NULL )
XCVAR_DEF( cg_debugScoreboard,				"0",					CVAR_NONE,					NULL )
XCVAR_DEF( cg_deferPlayers,					"1",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_delagHitscan,					"1",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_draw2D,						"1",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_draw3dIcons,					"0",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_drawAmmoWarning,				"1",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_drawRewards,					"1",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_drawAttacker,					"0",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_drawCrosshair,				"1",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_drawCrosshairNames,			"1",					CVAR_ARCHIVE,				NULL )
//XCVAR_DEF( cg_drawFlagCarrier,				"1",					CVAR_ARCHIVE )
XCVAR_DEF( cg_drawFPS,						"1",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_drawGun,						"1",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_drawIcons,					"1",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_drawPing,						"1",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_drawSnapshot,					"0",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_drawStatus,					"1",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_drawTeamOverlay,				"1",					CVAR_ARCHIVE|CVAR_USERINFO,	NULL )
XCVAR_DEF( cg_drawTimer,					"1",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_errorDecay,					"100",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_flagScale,					"0.5",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_forceAllyModel,				"none",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_forceAllyModelColor,			"0.5 0.5 0.5 1.0",		CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_forceEnemyModel,				"none",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_forceEnemyModelColor,			"0.0 1.0 0.0 1.0",		CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_footsteps,					"1",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_fov,							"90",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_gibs,							"1",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_gunAlign,						"0 0 0",				CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_gunBob,						"0.005 0.01 0.005",		CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_gunBobEnable,					"1",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_gunIdleDrift,					"0.01 0.01 0.01 0.004",	CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_gunIdleDriftEnable,			"1",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_gunZoomAlign,					"-2.0 4.0 2.35",		CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_hudFiles,						"ui/hud.txt",			CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_instantDuck,					"1",					CVAR_ARCHIVE,				NULL )
//XCVAR_DEF( cg_itemPickupTime,				"3500",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_lagometer,					"1",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_lagometerPos,					"592 432",				CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_marks,						"1",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_noTaunt,						"0",					CVAR_ARCHIVE,				NULL )
//XCVAR_DEF( cg_obituary,					"1",					CVAR_ARCHIVE,				NULL )
//XCVAR_DEF( cg_obituaryTime,				"5000",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_predictItems,					"1",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_runpitch,						"0.002",				CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_runroll,						"0.005",				CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_scorePlums,					"1",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_shadows,						"1",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_simpleItems,					"1",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_smoothClients,				"0",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_swingSpeed,					"0.3",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_teamChatsOnly,				"0",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_teamChatTime,					"3000",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_timescaleFadeEnd,				"1",					CVAR_NONE,					NULL )
XCVAR_DEF( cg_timescaleFadeSpeed,			"0",					CVAR_NONE,					NULL )
XCVAR_DEF( cg_trueLightning,				"1.0",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_viewBob,						"0.002 0.002 0.005 1",	CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_viewBobEnable,				"0",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_zoomFov,						"60",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cg_zoomTime,						"0.55",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( cl_paused,						"0",					CVAR_ROM,					NULL )
XCVAR_DEF( com_cameraMode,					"0",					CVAR_CHEAT,					NULL )
XCVAR_DEF( timescale,						"1",					CVAR_NONE,					NULL )
XCVAR_DEF( ui_bigFont,						"0.4",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( ui_smallFont,					"0.25",					CVAR_ARCHIVE,				NULL )
XCVAR_DEF( pm_fixed,						"0",					CVAR_SYSTEMINFO,			NULL )
XCVAR_DEF( pm_frametime,					"8",					CVAR_SYSTEMINFO,			NULL )
XCVAR_DEF( pm_snapVec,						"0",					CVAR_SYSTEMINFO,			NULL )
XCVAR_DEF( pm_overbounce,					"0",					CVAR_SYSTEMINFO,			NULL )
XCVAR_DEF( pm_landAccelerateEnable,			"1",					CVAR_SYSTEMINFO,			NULL )
XCVAR_DEF( pm_rampJumpEnable,				"1",					CVAR_SYSTEMINFO,			NULL )
XCVAR_DEF( pm_wallJumpEnable,				"1",					CVAR_SYSTEMINFO,			NULL )
XCVAR_DEF( pm_wallJumpDebounce,				"900",					CVAR_SYSTEMINFO,			NULL )
XCVAR_DEF( pm_bunnyHopEnable,				"1",					CVAR_SYSTEMINFO,			NULL )
XCVAR_DEF( pm_bunnyHopDebounce,				"250",					CVAR_SYSTEMINFO,			NULL )
XCVAR_DEF( pm_doubleJumpEnable,				"1",					CVAR_SYSTEMINFO,			NULL )
XCVAR_DEF( pm_doubleJumpPush,				"130",					CVAR_SYSTEMINFO,			NULL )
XCVAR_DEF( pm_doubleJumpDebounce,			"300",					CVAR_SYSTEMINFO,			NULL )
XCVAR_DEF( pm_accelerate,					"12.0",					CVAR_SYSTEMINFO,			NULL )
XCVAR_DEF( pm_airaccelerate,				"0.75",					CVAR_SYSTEMINFO,			NULL )
XCVAR_DEF( pm_friction,						"10.0",					CVAR_SYSTEMINFO,			NULL )
XCVAR_DEF( pm_jumpVelocity,					"250.0",				CVAR_SYSTEMINFO,			NULL )
XCVAR_DEF( pm_airControlEnable,				"1",					CVAR_SYSTEMINFO,			NULL )
XCVAR_DEF( pm_airControl,					"100.0",				CVAR_SYSTEMINFO,			NULL )
XCVAR_DEF( pm_airControlStopAccelerate,		"2.5",					CVAR_SYSTEMINFO,			NULL )
XCVAR_DEF( pm_airControlWishspeed,			"15",					CVAR_SYSTEMINFO,			NULL )
XCVAR_DEF( pm_airControlStrafeAccelerate,	"100",					CVAR_SYSTEMINFO,			NULL )

#undef XCVAR_DEF
